<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.24">
  <POU Name="FB_TxtLogger" Id="{b64d3bd5-8a36-4960-8962-cec44a61b481}">
    <Declaration><![CDATA[{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK INTERNAL FB_TxtLogger IMPLEMENTS ILogger
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Write" Id="{228a2bba-1d4f-4698-a869-5e758d44a93a}">
      <Declaration><![CDATA[METHOD PUBLIC Write : STRING
VAR_INPUT
	sMsg : STRING;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Write := CONCAT('TxtLogger: ', sMsg);
]]></ST>
      </Implementation>
    </Method>
    <ObjectProperties />
  </POU>
</TcPlcObject>